name = "FastLocalCorrelationCoefficients"
uuid = "a52d4850-34f0-40c4-bafd-3adb601f862f"
authors = ["Nikos Pitsianis <nikos@cs.duke.edu> and contributors"]
version = "0.1.2"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DSP = "0.7"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
