name: Documentation
on:
  push:
    branches:
      - master
    paths:
      - "**.jl"
      - "docs/**"
  pull_request:
    branches:
      - master
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using FastLocalCorrelationCoefficients
            DocMeta.setdocmeta!(FastLocalCorrelationCoefficients, :DocTestSetup, :(using FastLocalCorrelationCoefficients); recursive=true)
            doctest(FastLocalCorrelationCoefficients)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
